FROM images.gcihub.com/dig-basejmeter
LABEL Description="This pulls the jmeter base docker image and exposes the required ports for use as Master node"
#Port 60000 required for JMeter Master
EXPOSE 60000

